defaults:
  - _self_

tokenizer:
  name: "openai/whisper-small"

datasets:
  hf:
    train_clean_split: "train.360"
    train_other_split: "train.500"
    val_clean_split: "validation"
    val_other_split: "validation"
    lengths: [104014, 148688]

dataloader:
  batch_size_train: 32
  batch_size_val: 16
  num_workers: 4
  collate_fn:
    _target_: src.datasets.collate.collate_fn

model:
  encoder:
    _target_: src.models.models.Encoder
  decoder:
    _target_: src.models.models.Decoder

trainer:
  device: auto
  pad_id: 50256
  eos_id: 50257
  bos_id: 50258
  notimestamps_id: 50363
  vocab_size: 51865
  start_lr: 1e-4
  num_epochs: 100
  log_interval: 100
  examples_per_log: 3
  eval_batches: 10
  seed: 1
  run_name: "default_run"
  start_epoch: 0

pretrained:
  enabled: False
  encoder_link: "https://drive.google.com/uc?export=download&id=1UpX3_UgrbRTWYunAMHPsR09a1_zHzj7E"
  decoder_link: "https://drive.google.com/uc?export=download&id=1A1Cb1TCn5LWYuIADkOsfvzlBBBi2L2bi"