defaults:
  - mode: hf  
  - _self_

tokenizer:
  name: "openai/whisper-small"

dataloader:
  num_workers: 4

model:
  encoder:
    _target_: src.models.models.Encoder
  decoder:
    _target_: src.models.models.Decoder

inferencer:
  seed: 1
  device: auto           
  batch_size: 16        
  pad_id: 50256
  beam_size: 5
  skip_model_load: false 
  output_dir: "inference_predictions" 